### ISSUE TITLE
rain_exposure function can't work

### ISSUE THREAD

**Issue by my1120** [geanders/hurricaneexposure#21]
The first parameter is "locations" in the function codes in GitHub. However, the parameter name is "counties" in RStudio. I guess the inconsistency of parameter name is the reason for the errors by rain_exposure function.

**Comment by geanders** [comment]
Sorry about that. I changed the running of some of those functions when I made it so you can do multi-county communities. I just updates the vignette for you:

https://github.com/geanders/hurricaneexposure/blob/master/vignettes/hurricaneexposure.Rmd

Try out the examples and that and see if that works for you. Notice that now you'll use `locations` increase of `counties` for `rain_exposure`, because now that can either be a vector of FIPS codes, for counties, or a dataframe with community names and FIPS codes for each, for multi-county communities.

**Comment by my1120** [comment]
Thank you, Dr. Anderson.

It still didn’t work. The error is “unused locations”. Seems the name of parameter is “counties”. So I removed the package from my RStudio and try to reinstall. However, I got the error:

Error: processing vignette 'hurricaneexposure.Rmd' failed with diagnostics:
cannot open the connection
Execution halted
Error: Command failed (1)

Thank you!

Best,
Meilin

On Mar 1, 2016, at 6:46 PM, Brooke Anderson <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry about that. I changed the running of some of those functions when I made it so you can do multi-county communities. I just updates the vignette for you:

https://github.com/geanders/hurricaneexposure/blob/master/vignettes/hurricaneexposure.Rmd

Try out the examples and that and see if that works for you. Notice that now you'll use locations increase of counties for rain_exposure, because now that can either be a vector of FIPS codes, for counties, or a dataframe with community names and FIPS codes for each, for multi-county communities.

**Comment by geanders** [comment]
Okay, no problem, we'll take a look during our meeting today and get it sorted out!

Best,

Brooke

**Comment by geanders** [comment]
@my1120: Would you try installing the package from GitHub again, and see if you are still getting problems with the vignette?

**Comment by my1120** [comment]
No problem!

On May 20, 2016, at 5:12 PM, Brooke Anderson <notifications@github.com<mailto:notifications@github.com>> wrote:

@my1120https://github.com/my1120: Would you try installing the package from GitHub again, and see if you are still getting problems with the vignette?
